const NANOSECONDS = 1;
// const MICROSECONDS = 1000 * NANOSECONDS;
// const MICROSECONDS = 1;
const MILLISECONDS = 1;
const SECONDS = 1000 * MILLISECONDS;
const MINE_RATE = 4 * SECONDS;

export { MILLISECONDS };
export { SECONDS, MINE_RATE };
